name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Docker Login
      uses: docker/login-action@v4.2.0
      with:
        username: ${{ secrets.DOCKERACC }}
        password: ${{ secrets.DOCKERPWD }}
    - name: Build and Push
      run: |
        docker build . --file Dockerfile --tag rzdpai/huawei_cloud_webdav:latest
        docker push rzdpai/huawei_cloud_webdav:latest
